title: What do I think
email: ravgeetdhillon@gmail.com
description: This is Ravgeet's Blog.
author: Ravgeet Dhillon
baseurl: ""
url: "https://ravgeetdhillon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
  - README.md
  - compile-sass.sh
  - structurize.sh

collections:
  blog:
    output: true

defaults:
  - scope:
      type: blog
    values:
      layout: blog_post
      permalink: blog/:name/

feed:
  collections:
    blog:
      path: "/blog/feed.xml"