title: Ravgeet Dhillon - Developer & Writer
email: ravgeetdhillon@gmail.com
description: I design and develop websites, contribute to Open Source, play Fantasy Premier League with AI, write tutorials, and blogs for the community.
author: Ravgeet Dhillon

baseurl: /
url: https://ravgeetdhillon.github.io
site_repo: https://github.com/ravgeetdhillon/ravgeetdhillon.github.io

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
  - README.md
  - '*.sh'
  - LICENSE

collections:
  blog:
    output: true
  pages:
    output: true
  notes:
    output: false

defaults:
  - scope:
      type: blog
    values:
      layout: blog-post
      permalink: blog/:name/

feed:
  collections:
    blog:
      path: "/blog/feed.xml"
