title: Ravgeet Dhillon | Web Developer, Designer
email: ravgeetdhillon@gmail.com
description: Hello! I'm Ravgeet Dhillon and I develop exciting things that run on Web. I see myself as a Web Developer who creates best of the experiences for the people whenever he develops something new.
author: Ravgeet Dhillon
baseurl: /
url: https://ravgeetdhillon.github.io
site_repo: https://github.com/ravgeetdhillon/ravgeetdhillon.github.io
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  # - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
  - README.md
  - compile-sass.sh
  - structurize.sh

collections:
  blog:
    output: true
  pages:
    output: true

defaults:
  - scope:
      type: blog
    values:
      layout: blog_post
      permalink: blog/:name/

feed:
  collections:
    blog:
      path: "/blog/feed.xml"
