title: Ravgeet Dhillon - Web Development, Web Design, Automation, Open Source
email: ravgeetdhillon@gmail.com
description: Ravgeet Dhillon works on Web Development, Web Design, Automation, Open Source, and write blogs for the community.
author: Ravgeet Dhillon

baseurl: /
url: https://www.ravgeet.dev
site_repo: https://github.com/ravgeetdhillon/ravgeet.dev

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
  - README.md
  - '*.sh'
  - LICENSE

collections:
  blog:
    output: true
  pages:
    output: true
  notes:
    output: false
  projects:
    output: true

defaults:
  - scope:
      type: blog
    values:
      layout: blog-post
      permalink: blog/:name/
      navbar_color: bg-theme-white
  - scope:
      type: projects
    values:
      layout: project-post
      permalink: projects/:name/
      navbar_color: bg-theme-white

feed:
  collections:
    blog:
      path: "/blog/feed.xml"
