title: Full Stack Developer, Flutter Developer, Technical Content Writer - Ravgeet Dhillon

description: Ravgeet Dhillon is a Full Stack Developer, Flutter Developer, and Technical Content Writer based in India.

author: Ravgeet Dhillon

google:
  analytics_code: G-5P5CKH4GH2

site_repo: https://github.com/ravgeetdhillon/ravgeet-web

baseurl: ""

url: https://www.ravgeet.in

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
  - README.md
  - "*.sh"
  - netlify.toml

collections_dir: collections

collections:
  pages:
    output: true
  projects:
    output: true
  assets:
    output: true
  misc:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project
      type: project
      permalink: projects/:name/
  - scope:
      type: misc
    values:
      index: noindex

extlinks:
  attributes: { rel: "nofollow noreferrer" }
  rel_exclude: ["ravgeet.in", "ravsam.in"]

show_notifications: false
