title: Ravgeet Dhillon | Web Developer, Designer
email: ravgeetdhillon@gmail.com
description: I develop websites, contribute to Open Source, write algorithms for Self-driving cars, play Fantasy Premier League with AI, write tutorials, and blogs for the community.
author: Ravgeet Dhillon

baseurl: /
url: https://ravgeetdhillon.github.io
site_repo: https://github.com/ravgeetdhillon/ravgeetdhillon.github.io

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
  - README.md
  - compile-sass.sh
  - structurize.sh
  - start-server.sh
  - LICENSE

collections:
  blog:
    output: true
  pages:
    output: true
  notes:
    output: true

defaults:
  - scope:
      type: blog
    values:
      layout: blog-post
      permalink: blog/:name/

feed:
  collections:
    blog:
      path: "/blog/feed.xml"
