[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/resume"
status = 301
to = "/files/ravgeet-dhillon-resume.pdf"

[[redirects]]
from = "/cover-letter"
status = 301
to = "/files/ravgeet-dhillon-cover-letter.pdf"

# historic
[[redirects]]
force = false
from = "https://www.ravgeet.in/assets/*"
status = 301
to = "https://www.ravgeet.in/files/:splat"

# basic redirect for spa hosted on netlify
[[redirects]]
from = "/*"
status = 200
to = "/index.html"

# historic
[[redirects]]
force = false
from = "/about/"
status = 301
to = "/story"

# these are used by blog.ravgeet.in keep them here
# historic
# [[redirects]]
# force = false
# from = "https://blog.ravgeet.in/"
# status = 301
# to = "https://www.ravgeet.in/blog"

# historic
# [[redirects]]
# force = false
# from = "https://blog.ravgeet.in/:splat"
# status = 301
# to = "https://www.ravgeet.in/blog/*"
