name: Build and Deploy

on:
  push:
    branches:
      - master
  schedule:
  - cron: '0 0 * * *'

jobs:
  buildWebsite:

    env:
      REMOTE_BRANCH: gh-pages
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v1
        
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
      
    - name: Install NPM packages
      run: |
        npm install

    - name: Structurize website
      run: |
        bash structurize.sh
      
    - name: Compile SASS
      run: |
        npm run compile-sass

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    
    - name: Install Gems
      run: |
        gem install bundler -v 2.0.1
        bundle install
      
    - name: Build website
      run: |
        bundle exec jekyll build -d public

    - name: Upload website build
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: public

    - name: Configure Git
      run: |
        git checkout -f ${REMOTE_BRANCH}
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
    - name: Download website build
      uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./

    - name: Commit and Push
      run: |
        git add -f .
        git commit -m "gh-actions updated website"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
