name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  buildWebsite:

    env:
      REMOTE_BRANCH: master
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v1
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
      
    - name: Install NPM packages
      run: |
        npm install

    - name: Structurize website
      run: |
        bash structurize.sh
      
    - name: Compile SASS
      run: |
        npm run compile-sass
      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.5
    
    - name: Install PIP Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Optimize images
      run: |
        python optimize.py
        
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: master
        FOLDER: ./

#     - name: Configure Git
#       run: |
#         git config --global user.email ${GITHUB_ACTOR}@gmail.com
#         git config --global user.name ${GITHUB_ACTOR}

#     - name: Commit and Push
#       run: |
#         git add -f assets
#         git commit -m "gh-actions updated website assets"
#         git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
