name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  buildWebsite:
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v1
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
      
    - name: Install NPM packages
      run:
        npm install

    - name: Structurize website
      run:
        bash structurize.sh
      
    - name: Compile SASS
      run:
        npm run compile-css

    - name: Commit and Push
      run: |
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
        change=`git diff --exit-code assets`
        change=`echo $?`
        if [ $change -eq 1 ]
        then
            git add assets
            git commit -m "gh-actions updated website assets"
            git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
        fi
      env:
        REMOTE_BRANCH: master

    - name: Trigger GitHub Pages build
      run:
        bash gh-pages-build.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
