name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install GEM Dependencies
      run: |
        gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
        bundle install

    - name: Install NPM packages
      run: |
        npm install
    
    - name: Optimize website
      run: |
        bash structurize.sh
        npm run compile-css
    
    - name: Build website
      run: |
        bundle exec jekyll build -d public

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: public

  pushWebsite:
    needs: build
    runs-on: ubuntu-latest
    env:
      REMOTE_BRANCH: website
    
    steps:
    - name: Clone the repoitory
      uses: actions/checkout@v1
    
    - name: Configure Git
      run: |
        git checkout -f ${REMOTE_BRANCH}
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
    - name: Remove data
      run: |
        rm -rf public
    
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: public
        path: public
    
    - name: Commit and Push
      run: |
        git add -f public
        git commit -m "gh-actions updated website"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}